version: '3.8'

services:
  postgres_master:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eLibrary
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
    networks:
      - pg_network

  postgres_replica:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eLibrary
      POSTGRES_MASTER_HOST: postgres_master
      POSTGRES_MASTER_PORT: 5432
    ports:
      - "5433:5432"
    depends_on:
      - postgres_master
    networks:
      - pg_network

volumes:
  master_data:

networks:
  pg_network:
